


# ----- Causal Testbed -----



# Functions for simulating observational data to test sensitivity 
# analysis for hidden bias



# Determines whether a person gets sick given
# their age, sex, and vaccine status
determine_outcome <- function(age, sex, vaccine){
  mu <- (0.3 * sex) + (-0.01 * age) + (0.2 * vaccine)
  p <- 1 / (1 + exp(-mu))
  return(ifelse(p >= 0.5, 1, 0))
}

# Population characteristics for age
determine_age <- function(n){
  age <- 0.82 * rbeta(n, 2, 5) + 0.18
  return(round(100 * age))
}

# Population characteristics for people's sex
determine_sex <- function(n){
  return(sample(c(1, 0), n, prob = c(0.505, 0.495), replace = TRUE))
}

# Generate observational data
obs_dgp <- function(n){
  
  # Step 1. Get subject age(s) and sex(s)
  subject_age <- determine_age(n)
  subject_sex <- determine_sex(n)
  
  # Step 2. Vaccines are assigned by a healthcare policy
  # Older people are more likely to get a vaccine
  # Men are more likely to get a vaccine
  # In practice we would not know what this policy is
  # Note that this is still a random assignment, but it is random based on age and sex
  mu_1 <- -0.1 + (-0.2 * subject_sex) + (0.005 * subject_age) + rnorm(n, 0, 0.05)
  pV_1 <- 1 / (1 + exp(-mu_1))
  subject_vaccine <- ifelse(pV_1 >= 0.5, 1, 0)
  
  # Step 3. We wait a year to see if the patient remains healthy
  # To do this we will pass the subject info to the function we made that 
  # determines what happens to each person
  subject_outcome <- determine_outcome(
    age = subject_age,
    sex = subject_sex,
    vaccine = subject_vaccine
  )
  
  # Now we return the data that was generated by the DGP as a data frame
  subject_data <- data.frame(
    age = subject_age,
    sex = subject_sex,
    vaccine = subject_vaccine,
    outcome = subject_outcome
  )
  return(subject_data)
  
}
